---
swagger: "2.0"
info:
  version: "1.0"
  title: "docuinfo-accounts"
host: "18.196.197.222"
basePath: "/accounts"
schemes:
- "http"
paths:
  /create_account:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - email
              - password
              - data
            properties:
              email:
                type: string
              password:
                type: string
                description: "Minimum eight characters, lowercase letter, uppercase letter and number required"
              data:
                type: object
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /update_account:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - data
            properties:
              token:
                type: string
              data:
                type: object
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_account:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "account": { }
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /change_email:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - newEmail
            properties:
              token:
                type: string
              newEmail:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /request_password:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - email
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /reset_password:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - newPassword
            properties:
              token:
                type: string
              newPassword:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /change_password:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - password
              - newPassword
            properties:
              token:
                type: string
              password:
                type: string
              newPassword:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /delete_account:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - password
            properties:
              token:
                type: string
              password:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /upload_photo:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - photoBase64
            properties:
              token:
                type: string
              photoBase64:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /delete_photo:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /send_feedback:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - version
              - appName
              - feedback
            properties:
              token:
                type: string
              version:
                type: string
              appName:
                type: string
              feedback:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /confirm_email:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }