swagger: '2.0'
info:
  version: '1.0'
  title: docuinfo-templates
host: xz0mqolc0d.execute-api.eu-central-1.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /create_template:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - companyID
              - name
              - fields
            properties:
              token:
                type: string
              companyID:
                type: integer
              name:
                type: string
              fields:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "templateID": 0
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_templates:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - companyID
            properties:
              token:
                type: string
              companyID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "templates": [{ }]
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /edit_template:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - templateID
              - fields
            properties:
              token:
                type: string
              templateID:
                type: integer
              fields:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /delete_template:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - templateID
            properties:
              token:
                type: string
              templateID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }