---
swagger: "2.0"
info:
  version: "1.0"
  title: "docuinfo-workers"
host: "t3zri76bd2.execute-api.eu-central-1.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /add_worker:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - workerEmail
            properties:
              token:
                type: string
              workerEmail:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_workers:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "workers": []
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /assign_worker:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - workerID
              - groupID
            properties:
              token:
                type: string
              workerID:
                type: integer
              groupID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /remove_worker:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - workerID
            properties:
              token:
                type: string
              workerID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /invite_worker:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - email
              - from
              - to
              - message
            properties:
              token:
                type: string
              email:
                type: string
              from:
                type: string
              to:
                type: string
              message:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
