---
swagger: "2.0"
info:
  version: "1.0"
  title: "docuinfo-authentication"
host: "3ci8uvvcik.execute-api.eu-central-1.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /login:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "token": "TOKEN",
            "data": { },
            "subscribed" : true
            }
        '400':
          description: |-
            {
            "errorCode" : 0
            }
  /logout:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "errorCode" : 0
            }
