swagger: '2.0'
info:
  version: '1.0'
  title: docuinfo-organizations
host: attydpd6w8.execute-api.eu-central-1.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /get_organizations:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
            properties:
              token:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "organizations": [{ }]
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /leave_organization:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - organizationID
            properties:
              token:
                type: string
              organizationID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
