swagger: '2.0'
info:
  version: '1.0'
  title: docuinfo-templates
host: xz0mqolc0d.execute-api.eu-central-1.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /create_template:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - companyID
              - name
              - fields
              - signatures
            properties:
              token:
                type: string
              companyID:
                type: integer
              name:
                type: string
              fields:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    options:
                      type: array
                      items:
                        type: string
              signatures:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    displayDate:
                      type: boolean
            example:
              token: 5P13RD4L4J5L3D21U
              companyID: 0
              name: Food order example template
              fields: [
                {name: Food order, type: header},
                {name: Your name, type: string},
                {name: Your order, type: choice, options: [Kebab, Pizza, Hot Dog]},
                {name: Delivery time, type: time}
              ]
              signatures: [
                {name: Car owner, displayDate: false},
                {name: Customer, displayDate: true}
              ]
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "templateID": 0
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_templates:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - companyID
            properties:
              token:
                type: string
              companyID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "templates": [{ }]
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /edit_template:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - templateID
              - fields
            properties:
              token:
                type: string
              templateID:
                type: integer
              fields:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    options:
                      type: array
                      items: 
                        type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /delete_template:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - templateID
            properties:
              token:
                type: string
              templateID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
