swagger: '2.0'
info:
  version: '1.0'
  title: docuinfo-templates
host: xz0mqolc0d.execute-api.eu-central-1.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /get_templates:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - companyID
            properties:
              token:
                type: string
              companyID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "templates": [{ }]
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }