swagger: '2.0'
info:
  version: '1.0'
  title: docuinfo-protocols
host: numwv2ufy7.execute-api.eu-central-1.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /create_protocol:
    post:
      description: "Create protocol"
      parameters:
        - in: body
          name: body
          schema: 
            properties:
              token:
                type: string
              creationDate:
                type: string
                format: date-time
              locationID:
                type: integer
              geoLocation:
                type: object
                properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
              fields:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    value:
                      type: string
              data:
                type: object
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "protocolID" : x
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_protocols:
    post:
      description:
        Get protocols
      parameters:
        - in: body
          name: body
          schema:
            properties:
              token:
                type: string
              locationID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "protocols": [{ }]
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /delete_protocol:
    post:
      description:
        Delete protocol
      parameters:
        - in: body
          name: body
          schema: 
            properties:
              token:
                type: string
              protocolID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /upload_photo:
    post:
      description:
        Upload photo
      parameters:
        - in: body
          name: body
          schema: 
            properties:
              token:
                type: string
              protocolID:
                type: integer
              photoBase64:
                type: string
              filename:
                type: string
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_photos:
    post:
      description:
        Get photos
      parameters:
        - in: body
          name: body
          schema: 
            properties:
              token:
                type: string
              protocolID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            "photos" : []
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  
