swagger: '2.0'
info:
  version: '1.0'
  title: docuinfo-protocols
host: numwv2ufy7.execute-api.eu-central-1.amazonaws.com
basePath: /Prod
schemes:
  - https
paths:
  /create_protocol:
    post:
      summary: Create protocol
      description: ''
      parameters:
        - in: body
          name: body
          schema: 
            type: object
            properties:
              token:
                type: string
              creationDate:
                type: string
                format: date-time
              locationID:
                type: integer
              geoLocation:
                type: object
                properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
              fields:
                type: array
                items: 
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    value:
                      type: string
              data:
                type: object
            example:
              token: 5P13RD4L4J5L3D21U
              creationDate: "2018-01-01 21:37"
              locationID: 0
              geoLocation: {latitude: 0, longitude: 0}
              fields: [
                {name: Food order, type: header},
                {name: Your name, type: string, value: Maciej Nowak},
                {name: Your order, type: choice, value: Spaghetti},
                {name: Delivery time, type: time, value: "22:22"},
              ]
              data: {} #developer specified data
              
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "protocolID" : x
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_protocols:
    post:
      summary: Get protocols
      description: ''
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              token:
                type: string
              locationID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success",
            "protocols": [{ }]
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /delete_protocol:
    post:
      summary: Delete protocol
      description: ''
      parameters:
        - in: body
          name: body
          schema: 
            type: object
            properties:
              token:
                type: string
              protocolID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /export_protocol:
    post:
      summary: Export protocol
      description: ''
      parameters:
        - in: body
          name: body
          schema: 
            type: object
            properties:
              token:
                type: string
              protocolID:
                type: integer
              language:
                type: string
            example:
              token: 5P13RD4L4J5L3D21U
              protocolID: 0
              language: de
      responses:
        '200':
          description: |-
            {
            "protocol" : "protocol"
            "message" : "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /upload_photo:
    post:
      summary: Upload photo
      description: ''
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              token:
                type: string
              protocolID:
                type: integer
              photoBase64:
                type: string
              filename:
                type: string
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
  /get_photos:
    post:
      summary: Get photos
      description: ''
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              token:
                type: string
              protocolID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message" : "success"
            "photos" : []
            }
        '400':
          description: |-
            {
            "error" : "error message"
            }
